GET http://{{host}}:{{port}}/test1

###
GET http://{{host}}:{{port}}/test2

###
GET http://{{host}}:{{port}}/test3

###
GET http://{{host}}:{{port}}/test4

###
GET http://{{host}}:{{port}}/test5

###
GET http://{{host}}:{{port}}/date

###
GET http://{{host}}:{{port}}/natural

###
GET http://{{host}}:{{port}}/integer

###
GET http://{{host}}:{{port}}/float

###
GET http://{{host}}:{{port}}/image
