export enum Taps {random = "random", mock = "mock"}

export enum MethodNames {
  boolean = "boolean",
  natural = "natural",
  integer = "integer",
  float = "float",
  character = "character",
  string = "string",
  range = "range",
  date = "date",
  time = "time",
  datetime = "datetime",
  now = "now",
  image = "image",
  dataImage = "dataImage",
  color = "color",
  paragraph = "paragraph",
  sentence = "sentence",
  word = "word",
  title = "title",
  cparagraph = "cparagraph",
  csentence = "csentence",
  cword = "cword",
  ctitle = "ctitle",
  first = "first",
  last = "last",
  name = "name",
  cfirst = "cfirst",
  clast = "clast",
  cname = "cname",
  url = "url",
  domain = "domain",
  email = "email",
  ip = "ip",
  tld = "tld",
  area = "area",
  region = "region",
  capitalize = "capitalize",
  upper = "upper",
  lower = "lower",
  pick = "pick",
  shuffle = "shuffle",
  guid = "guid",
  id = "id"
}